apiVersion: v1
kind: Service
metadata:
  name: irrigation-frontend
  namespace: irrigation-system
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30200
    protocol: TCP
    name: http
  selector:
    app: irrigation-frontend
