apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: irrigation-system
spec:
  type: NodePort
  ports:
  - port: 9095
    targetPort: 9095
    nodePort: 30888
    protocol: TCP
    name: http
  selector:
    app: gateway
